.PHONY: help build run clean test esp32-config esp32-build

help: ## Show this help
	@grep -E '^[a-zA-Z0-9_-]+:.*##' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*##"}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

build: ## Build the Go server binary
	go build -o bin/therm-pro-server ./cmd/therm-pro-server

run: ## Run the Go server (no build)
	go run ./cmd/therm-pro-server

test: ## Run all Go tests
	go test ./...

clean: ## Remove build artifacts
	rm -rf bin/

esp32-config: ## Generate esp32/src/config.h from env vars (ESP32_WIFI_SSID, ESP32_WIFI_PASS, ESP32_SERVER_URL)
	@if [ -z "$$ESP32_WIFI_SSID" ]; then echo "ERROR: ESP32_WIFI_SSID is not set"; exit 1; fi
	@if [ -z "$$ESP32_WIFI_PASS" ]; then echo "ERROR: ESP32_WIFI_PASS is not set"; exit 1; fi
	@if [ -z "$$ESP32_SERVER_URL" ]; then echo "ERROR: ESP32_SERVER_URL is not set"; exit 1; fi
	@echo "// esp32/src/config.h (generated by make esp32-config)" > esp32/src/config.h
	@echo "#ifndef CONFIG_H" >> esp32/src/config.h
	@echo "#define CONFIG_H" >> esp32/src/config.h
	@echo "" >> esp32/src/config.h
	@echo "#define WIFI_SSID \"$$ESP32_WIFI_SSID\"" >> esp32/src/config.h
	@echo "#define WIFI_PASS \"$$ESP32_WIFI_PASS\"" >> esp32/src/config.h
	@echo "#define SERVER_URL \"$$ESP32_SERVER_URL\"" >> esp32/src/config.h
	@echo "#define FIRMWARE_VERSION $${ESP32_FIRMWARE_VERSION:-1}" >> esp32/src/config.h
	@echo "#define LED_PIN $${ESP32_LED_PIN:-2}" >> esp32/src/config.h
	@echo "" >> esp32/src/config.h
	@echo "#endif" >> esp32/src/config.h
	@echo "Generated esp32/src/config.h"

esp32-build: esp32-config ## Build ESP32 firmware (generates config.h first)
	cd esp32 && pio run
