.PHONY: help build run clean test fmt tidy esp32-config esp32-scan esp32-scan-name esp32-scan-diff esp32-build esp32-flash esp32-upload esp32-monitor esp32-all esp32c3-build esp32c3-flash esp32c3-upload esp32c3-all

help: ## Show this help
	@grep -E '^[a-zA-Z0-9_-]+:.*##' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*##"}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

GIT_COMMIT := $(shell git rev-parse HEAD 2>/dev/null || echo "unknown")

build: ## Build the Go server binary
	CGO_ENABLED=0 go build -ldflags "-X main.GitCommit=$(GIT_COMMIT)" -o bin/therm-pro-server ./cmd/therm-pro-server

run: ## Run the Go server (no build)
	CGO_ENABLED=0 go run ./cmd/therm-pro-server

test: ## Run all Go tests
	CGO_ENABLED=0 go test ./...

clean: ## Remove build artifacts
	rm -rf bin/

fmt: ## Format Go source files
	go fmt ./...

tidy: ## Tidy and verify Go module dependencies
	go mod tidy

esp32-config: ## Generate esp32/src/config.h from env vars (ESP32_WIFI_SSID, ESP32_WIFI_PASS; ESP32_SERVER_URL defaults to http://tp25.service.dc1.consul:8088). Sources esp32/.ble-config if present (written by `make esp32-scan`).
	@if [ -z "$$ESP32_WIFI_SSID" ]; then echo "ERROR: ESP32_WIFI_SSID is not set"; exit 1; fi
	@if [ -z "$$ESP32_WIFI_PASS" ]; then echo "ERROR: ESP32_WIFI_PASS is not set"; exit 1; fi
	@ENV_BLE_NAME="$$ESP32_BLE_NAME"; \
	ENV_BLE_SERVICE_UUID="$$ESP32_BLE_SERVICE_UUID"; \
	ENV_BLE_WRITE_CHAR_UUID="$$ESP32_BLE_WRITE_CHAR_UUID"; \
	ENV_BLE_NOTIFY_CHAR_UUID="$$ESP32_BLE_NOTIFY_CHAR_UUID"; \
	if [ -f esp32/.ble-config ]; then set -a; . ./esp32/.ble-config; set +a; fi; \
	BLE_NAME="$${ENV_BLE_NAME:-$${ESP32_BLE_NAME:-Thermopro}}"; \
	BLE_SERVICE_UUID="$${ENV_BLE_SERVICE_UUID:-$${ESP32_BLE_SERVICE_UUID:-1086fff0-3343-4817-8bb2-b32206336ce8}}"; \
	BLE_WRITE_CHAR_UUID="$${ENV_BLE_WRITE_CHAR_UUID:-$${ESP32_BLE_WRITE_CHAR_UUID:-1086fff1-3343-4817-8bb2-b32206336ce8}}"; \
	BLE_NOTIFY_CHAR_UUID="$${ENV_BLE_NOTIFY_CHAR_UUID:-$${ESP32_BLE_NOTIFY_CHAR_UUID:-1086fff2-3343-4817-8bb2-b32206336ce8}}"; \
	{ \
	  echo "// esp32/src/config.h (generated by make esp32-config)"; \
	  echo "#ifndef CONFIG_H"; \
	  echo "#define CONFIG_H"; \
	  echo ""; \
	  echo "#define WIFI_SSID \"$$ESP32_WIFI_SSID\""; \
	  echo "#define WIFI_PASS \"$$ESP32_WIFI_PASS\""; \
	  echo "#define SERVER_URL \"$${ESP32_SERVER_URL:-http://tp25.service.dc1.consul:8088}\""; \
	  echo "#define FIRMWARE_VERSION $${ESP32_FIRMWARE_VERSION:-1}"; \
	  echo "#define LED_PIN $${ESP32_LED_PIN:-2}"; \
	  echo ""; \
	  echo "#define BLE_NAME             \"$$BLE_NAME\""; \
	  echo "#define BLE_SERVICE_UUID     \"$$BLE_SERVICE_UUID\""; \
	  echo "#define BLE_WRITE_CHAR_UUID  \"$$BLE_WRITE_CHAR_UUID\""; \
	  echo "#define BLE_NOTIFY_CHAR_UUID \"$$BLE_NOTIFY_CHAR_UUID\""; \
	  echo ""; \
	  echo "#endif"; \
	} > esp32/src/config.h
	@echo "Generated esp32/src/config.h"

esp32-scan: ## Scan BLE for a Therm-Pro unit (probe + classify), write esp32/.ble-config, then regenerate config.h
	@CGO_ENABLED=1 go run ./cmd/therm-pro-scan \
		-probe \
		-timeout "$${ESP32_SCAN_TIMEOUT:-15s}" \
		-output esp32/.ble-config
	@$(MAKE) --no-print-directory esp32-config

esp32-scan-name: ## Scan by advertised name substring (default "thermo", override with ESP32_SCAN_NAME); writes esp32/.ble-config and regenerates config.h
	@CGO_ENABLED=1 go run ./cmd/therm-pro-scan \
		-name "$${ESP32_SCAN_NAME:-thermo}" \
		-timeout "$${ESP32_SCAN_TIMEOUT:-15s}" \
		-output esp32/.ble-config
	@$(MAKE) --no-print-directory esp32-config

esp32-scan-diff: ## Interactive two-pass diff scan; only shows devices that appeared after a power-cycle. Writes esp32/.ble-config and regenerates config.h
	@CGO_ENABLED=1 go run ./cmd/therm-pro-scan \
		-diff \
		-timeout "$${ESP32_SCAN_TIMEOUT:-15s}" \
		-output esp32/.ble-config
	@$(MAKE) --no-print-directory esp32-config

esp32-build: esp32-config ## Build ESP32 firmware (generates config.h first)
	cd esp32 && pio run -e esp32

esp32-flash: esp32-build ## Build and flash ESP32 via USB (uses espflash)
	espflash flash --chip esp32 esp32/.pio/build/esp32/firmware.elf

esp32-upload: esp32-build ## Build and upload firmware to server for OTA
	curl -X POST $${ESP32_SERVER_URL:-http://tp25.service.dc1.consul:8088}/api/firmware/upload \
		-F "firmware=@esp32/.pio/build/esp32/firmware.bin" \
		-F "version=$${ESP32_FIRMWARE_VERSION:-1}"

esp32-monitor: ## Monitor ESP32 serial output (uses espflash)
	espflash monitor

esp32-all: esp32-scan esp32-flash ## Scan, regenerate config.h, build, and flash ESP32 in one shot

esp32c3-build: esp32-config ## Build ESP32-C3 firmware (set ESP32_LED_PIN=8 for DevKitM-1)
	cd esp32 && pio run -e esp32c3

esp32c3-flash: esp32c3-build ## Build and flash ESP32-C3 via USB (uses espflash)
	espflash flash --chip esp32c3 esp32/.pio/build/esp32c3/firmware.elf

esp32c3-upload: esp32c3-build ## Build and upload ESP32-C3 firmware to server for OTA
	curl -X POST $${ESP32_SERVER_URL:-http://tp25.service.dc1.consul:8088}/api/firmware/upload \
		-F "firmware=@esp32/.pio/build/esp32c3/firmware.bin" \
		-F "version=$${ESP32_FIRMWARE_VERSION:-1}"

esp32c3-all: esp32-scan esp32c3-flash ## Scan, regenerate config.h, build, and flash ESP32-C3 in one shot
