.PHONY: help build run clean test fmt tidy esp32-config esp32-build esp32-flash esp32-upload esp32-monitor

help: ## Show this help
	@grep -E '^[a-zA-Z0-9_-]+:.*##' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*##"}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

GIT_COMMIT := $(shell git rev-parse HEAD 2>/dev/null || echo "unknown")

build: ## Build the Go server binary
	CGO_ENABLED=0 go build -ldflags "-X main.GitCommit=$(GIT_COMMIT)" -o bin/therm-pro-server ./cmd/therm-pro-server

run: ## Run the Go server (no build)
	CGO_ENABLED=0 go run ./cmd/therm-pro-server

test: ## Run all Go tests
	CGO_ENABLED=0 go test ./...

clean: ## Remove build artifacts
	rm -rf bin/

fmt: ## Format Go source files
	go fmt ./...

tidy: ## Tidy and verify Go module dependencies
	go mod tidy

esp32-config: ## Generate esp32/src/config.h from env vars (ESP32_WIFI_SSID, ESP32_WIFI_PASS; ESP32_SERVER_URL defaults to http://tp25.service.dc1.consul:8088)
	@if [ -z "$$ESP32_WIFI_SSID" ]; then echo "ERROR: ESP32_WIFI_SSID is not set"; exit 1; fi
	@if [ -z "$$ESP32_WIFI_PASS" ]; then echo "ERROR: ESP32_WIFI_PASS is not set"; exit 1; fi
	@echo "// esp32/src/config.h (generated by make esp32-config)" > esp32/src/config.h
	@echo "#ifndef CONFIG_H" >> esp32/src/config.h
	@echo "#define CONFIG_H" >> esp32/src/config.h
	@echo "" >> esp32/src/config.h
	@echo "#define WIFI_SSID \"$$ESP32_WIFI_SSID\"" >> esp32/src/config.h
	@echo "#define WIFI_PASS \"$$ESP32_WIFI_PASS\"" >> esp32/src/config.h
	@echo "#define SERVER_URL \"$${ESP32_SERVER_URL:-http://tp25.service.dc1.consul:8088}\"" >> esp32/src/config.h
	@echo "#define FIRMWARE_VERSION $${ESP32_FIRMWARE_VERSION:-1}" >> esp32/src/config.h
	@echo "#define LED_PIN $${ESP32_LED_PIN:-2}" >> esp32/src/config.h
	@echo "" >> esp32/src/config.h
	@echo "#endif" >> esp32/src/config.h
	@echo "Generated esp32/src/config.h"

esp32-build: esp32-config ## Build ESP32 firmware (generates config.h first)
	cd esp32 && pio run

esp32-flash: esp32-build ## Build and flash ESP32 via USB (uses espflash)
	espflash flash --chip esp32 esp32/.pio/build/esp32/firmware.elf

esp32-upload: esp32-build ## Build and upload firmware to server for OTA
	curl -X POST $${ESP32_SERVER_URL:-http://tp25.service.dc1.consul:8088}/api/firmware/upload \
		-F "firmware=@esp32/.pio/build/esp32/firmware.bin" \
		-F "version=$${ESP32_FIRMWARE_VERSION:-1}"

esp32-monitor: ## Monitor ESP32 serial output (uses espflash)
	espflash monitor
